GET http://localhost:4000/users

###
GET http://localhost:4000/users/1

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "npm": "50421085",
  "name": "Akbar Fitriadi",
  "kelas": "3IA17",
  "jurusan": "Teknik Informatika",
  "phone": "89512233408"
}

###
PATCH http://localhost:4000/users/1
Content-Type: application/json

{
  "npm": "50421000",
  "name": "Fitriadi",
  "kelas": "3IA17",
  "jurusan": "Teknik Informatika",
  "phone": "89512233408"
}

###
DELETE http://localhost:4000/users/1
